name: task_demo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  anim_search_bar: ^2.0.3
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  bot_toast: ^4.0.3
  flutter_dotenv: ^5.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

